version: 2.1
jobs:

  # installation of dependencies, Linter and tests
  linter_and_tests:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: flake8
      - run: pytest

  # Build the docker image
  build_and_push:
    docker:
      - image: cimg/base:2021.07    
    steps:
      # For using docker commands
      - setup_remote_docker:
          version: 19.03.13
      - checkout

      # Build the docker image      
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker build -t $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 --build-arg SENTRY_DSN=$SENTRY_DSN .
      - run: docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1

  #deploy to Heroku
  deploy_to_heroku:
    docker:
      - image: cimg/base:2021.07
    steps:
      # For using docker commands
      - setup_remote_docker:
          version: 19.03.13
      - checkout

      # Deploy to Heroku      
      - heroku/install
      - run: docker login --username=$HEROKU_USER --password=$HEROKU_API_KEY registry.heroku.com
      - run: heroku config:set -a $HEROKU_APP_NAME DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY SENTRY_DSN=$SENTRY_DSN 
      - run: heroku container:push web -a $HEROKU_APP_NAME
      - run: heroku container:release web -a $HEROKU_APP_NAME

orbs:
  # For using Heroku CLI commands
  heroku: circleci/heroku@2.0.0


workflows:
  build:
      jobs:
        - linter_and_tests        
        - build_and_push:
            requires:
              - linter_and_tests
            filters:
              branches:
                only:
                  - master

        - deploy_to_heroku:
            requires:
              - build_and_push
            
      