version: 2.1
jobs:
  # try
  lint_and_tests:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "What is SHA_1?"    
          command: echo $CIRCLE_SHA1

      - run:
          name: "Version de Python"
          command: python --version

  # Build the docker image and deploy it to Heroku.
  build_and_deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      # For using docker commands.
      - setup_remote_docker:
          version: 19.03.13

      # Build the docker image
      - checkout
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: docker build -t oc-lettings-site:$CIRCLE_SHA1 .
      - run: docker tag oc-lettings-site:$CIRCLE_SHA1 rv2476/oc-lettings-site:$CIRCLE_SHA1
      - run: docker push rv2476/oc-lettings-site:$CIRCLE_SHA1

      # Deploy to Heroku
      - heroku/install
      - run: heroku container:login
      - run: heroku git:remote -a oc-lettings-2476
      - run: heroku container:push web -a oc-lettings-2476
      - run: heroku container:release web -a oc-lettings-2476

orbs:
  # For using Heroku CLI commandｓ.
  heroku: circleci/heroku@1.2.6


workflows:
  build:
      jobs:
        - lint_and_tests        
        - build_and_deploy:
            filters:
              branches:
                only:
                  - master_old

      