# Generated by Django 3.0 on 2022-10-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20221006_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
